GET http://localhost:3000/evento?limite=10&desde=5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7InVzZXJuYW1lIjoiRmVybmFuZG8gSGVycmVyYSIsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwiaWQiOiI2MTBiMTc5YTg1OWZkMjQxYzQzN2U4NjkifSwiaWF0IjoxNjI4MzYwNDkzLCJleHAiOjE2Mjg1MzMyOTN9.EQHneM8mHIPRqqDbtBsS9HRLxMu21bnx_e0DJ6WW9Pw

